# Generated by Django 4.1.5 on 2023-01-19 15:54

import core.buddy_constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField()),
                ('period', models.CharField(choices=[(core.buddy_constants.TimePeriods['MONTHLY'], 'Monthly'), (core.buddy_constants.TimePeriods['WEEKLY'], 'Weekly'), (core.buddy_constants.TimePeriods['BIWEEKLY'], 'Bi-Weekly'), (core.buddy_constants.TimePeriods['QUARTERLY'], 'Quarterly')], default=core.buddy_constants.TimePeriods['MONTHLY'], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_planned', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_expense', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.expense')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.budget')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile')),
            ],
        ),
    ]
